# Node image
FROM node:truffle
# Maintainer
MAINTAINER Huy Dao <huy@littlstar.com>
# Create code directory
RUN mkdir /code
# Set working directory
WORKDIR /code
# Install Truffle
RUN npm install -g truffle
