version: '2'
services:
  ganachecli:
    image: trufflesuite/ganache-cli:latest
    command: "--seed littlstar -h 0.0.0.0"
    # Mnemonic: demise minimum cupboard jump there blast muscle guitar debris interest upset dose
    ports:
      - "8545:8545"
  farmer:
    image: ara/ara-farming
    command: bash -c "cd contract
      && truffle migrate
      && cp build/contracts/Farming.json ../local/contract-address.json
      && cd ..
      && node"
    stdin_open: true
    tty: true
    depends_on:
      - ganachecli
    volumes:
      - ./:/root/local
  requester:
      image: ara/ara-farming
      stdin_open: true
      tty: true
      depends_on:
        - farmer
      volumes:
        - ./:/root/local
