#!/bin/bash

conf="
[web3]
provider = ws://127.0.0.1:8546
"

# provider = ws://127.0.0.1:8546 ;; privatenet ws

echo "${conf}" > /root/.ararc

for repo in ara-identity; do
  git clone git@github.com:AraBlocks/${repo}.git
  if [ $? -ne 0 ]; then
    exit 1
  fi
  cd ${repo}
  npm install
  npm link
  cd ..
done

mkdir -p /root/.ara/keyrings

# Create identity
echo "test" | aid create

identity="
[network.identity]
whoami=$(aid list | cut -d$'\n' -f1)
root=/root/.ara/identities
keyring=/root/.ara/keyrings/keyring
"

echo "${identity}" >> /root/.ararc

cat /root/.ararc

echo added identity to .ararc
echo
echo

for network in feed server archiver resolver; do
  echo -ne "Creating network key for ${network}\n"
  echo "test" | ank -n ${network} -s "test"
done
